# 裁剪无用功能
DISTRO_FEATURES:remove = " \
    qt qt6 ptest \
    alsa pulseaudio audio sound \
    wayland x11 opengl es2 vulkan gtk \
    gobject-introspection \
    tpm tpm2 virtualization \
"

# 产品必需
DISTRO_FEATURES:append = " systemd ppp usbmodeswitch modemmanager"
INIT_MANAGER = "systemd"

# 优化
DEBUG_BUILD = "0"
INHIBIT_PACKAGE_DEBUG_SPLIT = "1"
INHIBIT_PACKAGE_STRIP = "0"

DISTRO_FEATURES:remove = "rust go"
RUST_ENABLE = "0"
GO_ENABLE = "0"
INHERIT:remove = "rust cargo go"
IMAGE_INSTALL:remove = "rust cargo libstd-rs go golang python3-maturin"

